## What is k-Nearest Neighbors

http://machinelearningmastery.com/tutorial-to-implement-k-nearest-neighbors-in-python-from-scratch/

The model for kNN is the entire training dataset. When a prediction is required for a unseen data instance, the kNN algorithm will search through the training dataset for the **k-most similar instances**. The prediction attribute of the most similar instances is summarized and returned as the prediction for the unseen instance.

The **similarity measure** is dependent on the type of data. For real-valued data, the Euclidean distance can be used. Other other types of data such as categorical or binary data, Hamming distance can be used.

In the case of **regression problems**, the average of the predicted attribute may be returned. In the case of **classification**, the most prevalent class may be returned.

### How to implement k-Nearest Neighbors in Python

- Handle Data: Open the dataset from CSV and split into test/train datasets.
- Similarity: Calculate the distance between two data instances.
- Neighbors: Locate k most similar data instances.
- Response: Generate a response from a set of data instances.

### 1. Data

In [1]:
# About the Iris dataset
feature_dict = {0: 'sepal length in cm',
                1: 'sepal width in cm',
                2: 'petal length in cm',
                3: 'petal width in cm'
               }
print(feature_dict)

{0: 'sepal length in cm', 1: 'sepal width in cm', 2: 'petal length in cm', 3: 'petal width in cm'}


In [2]:
# Reading in the dataset
import pandas as pd

df = pd.io.parsers.read_csv(
    #filepath_or_buffer='https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data', 
    filepath_or_buffer='iris.data',
    header=None, 
    sep=',', 
    )
df.columns = list(feature_dict.values()) + ['class label']
df.dropna(how="all", inplace=True) # to drop the empty line at file-end

df.tail()

sepal length in cm  sepal width in cm  petal length in cm  \
145                 6.7                3.0                 5.2   
146                 6.3                2.5                 5.0   
147                 6.5                3.0                 5.2   
148                 6.2                3.4                 5.4   
149                 5.9                3.0                 5.1   

     petal width in cm     class label  
145                2.3  Iris-virginica  
146                1.9  Iris-virginica  
147                2.0  Iris-virginica  
148                2.3  Iris-virginica  
149                1.8  Iris-virginica

In [3]:
import numpy as np

msk = np.random.rand(len(df)) < 0.66
train = df[msk]
test = df[~msk]

print(msk)
print(len(train))
print(len(test))

[ True False  True  True False False False  True  True False  True  True
  True  True  True  True  True  True  True  True  True  True  True False
  True False  True  True  True False  True  True  True  True  True  True
 False  True False  True  True  True  True  True False  True False False
  True  True  True False  True  True False  True  True  True  True  True
  True  True  True  True  True  True False  True  True  True  True  True
  True  True  True  True  True  True  True False  True False False False
  True  True  True False  True False False False  True  True  True False
  True False  True  True  True False False  True  True False  True  True
  True False  True False  True  True  True  True  True  True False  True
  True  True  True False  True False False  True False False  True False
  True  True  True  True  True False False  True False False False  True
  True  True  True  True  True  True]
107
43


### 2. Similarity

In [4]:
selected_instance = df.iloc[0]
print(selected_instance)

sepal length in cm            5.1
sepal width in cm             3.5
petal length in cm            1.4
petal width in cm             0.2
class label           Iris-setosa
Name: 0, dtype: object


In [5]:
import math

def euclideanDistance(row):
    global selected_instance
    distance = 0.0
    for i in range(len(selected_instance)-1): # the last one is class label.
        distance += pow((row[i] - selected_instance[i]), 2)
    return math.sqrt(distance)

In [6]:
euclidean_distances = df.apply(euclideanDistance, axis=1)

distance_frame = pd.DataFrame(data={"dist": euclidean_distances, "idx": euclidean_distances.index})

print(distance_frame)

         dist  idx
0    0.000000    0
1    0.538516    1
2    0.509902    2
3    0.648074    3
4    0.141421    4
5    0.616441    5
6    0.519615    6
7    0.173205    7
8    0.921954    8
9    0.469042    9
10   0.374166   10
11   0.374166   11
12   0.591608   12
13   0.994987   13
14   0.883176   14
15   1.104536   15
16   0.547723   16
17   0.100000   17
18   0.741620   18
19   0.331662   19
20   0.435890   20
21   0.300000   21
22   0.648074   22
23   0.469042   23
24   0.591608   24
25   0.547723   25
26   0.316228   26
27   0.141421   27
28   0.141421   28
29   0.538516   29
..        ...  ...
120  5.121523  120
121  4.028647  121
122  6.211280  122
123  4.109745  123
124  4.969909  124
125  5.312250  125
126  3.977436  126
127  4.007493  127
128  4.840455  128
129  5.097058  129
130  5.546170  130
131  6.014150  131
132  4.880574  132
133  4.160529  133
134  4.570558  134
135  5.788782  135
136  4.891830  136
137  4.606517  137
138  3.896152  138
139  4.796874  139
140  5.01996

### 3. Neighbors

In [7]:
distance_frame.sort_values("dist", inplace=True)

# find closest one
second_smallest = distance_frame.iloc[1]["idx"]
most_similar = df.loc[int(second_smallest)]
print(most_similar)

sepal length in cm            5.1
sepal width in cm             3.5
petal length in cm            1.4
petal width in cm             0.3
class label           Iris-setosa
Name: 17, dtype: object


In [8]:
# find k cloest ones
k = 5
for i in range(1, k+1):
    index = distance_frame.iloc[i]["idx"]
    dist = distance_frame.iloc[i]["dist"]
    row = df.loc[int(index)]
    print("index: {}; dist: {}".format(index, dist))
    print(row)
    print("=====")

index: 17.0; dist: 0.09999999999999998
sepal length in cm            5.1
sepal width in cm             3.5
petal length in cm            1.4
petal width in cm             0.3
class label           Iris-setosa
Name: 17, dtype: object
=====
index: 4.0; dist: 0.1414213562373093
sepal length in cm              5
sepal width in cm             3.6
petal length in cm            1.4
petal width in cm             0.2
class label           Iris-setosa
Name: 4, dtype: object
=====
index: 39.0; dist: 0.14142135623730964
sepal length in cm            5.1
sepal width in cm             3.4
petal length in cm            1.5
petal width in cm             0.2
class label           Iris-setosa
Name: 39, dtype: object
=====
index: 27.0; dist: 0.14142135623730995
sepal length in cm            5.2
sepal width in cm             3.5
petal length in cm            1.5
petal width in cm             0.2
class label           Iris-setosa
Name: 27, dtype: object
=====
index: 28.0; dist: 0.14142135623730995
sepal le

### 4. Response

In [9]:
index = []

for i in range(1, k+1):
    ind = distance_frame.iloc[i]["idx"]
    index.append(int(ind))
    
print(index)

[17, 4, 39, 27, 28]


In [10]:
for i in index:
    print(df.loc[i]["class label"], distance_frame.iloc[i]["dist"])

Iris-setosa 0.387298334621
Iris-setosa 0.141421356237
Iris-setosa 0.648074069841
Iris-setosa 0.538516480713
Iris-setosa 0.538516480713


## K-nn by sklearn 

In [11]:
import numpy as np
from sklearn import datasets

iris = datasets.load_iris()
iris_X = iris.data
iris_y = iris.target
np.unique(iris_y)

array([0, 1, 2])

In [12]:
np.random.seed(0)
indices = np.random.permutation(len(iris_X))
iris_X_train = iris_X[indices[:-10]]
iris_y_train = iris_y[indices[:-10]]
iris_X_test  = iris_X[indices[-10:]]
iris_y_test  = iris_y[indices[-10:]]

In [13]:
# Create and fit a nearest-neighbor classifier
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier()
knn.fit(iris_X_train, iris_y_train) 
KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=1, n_neighbors=5, p=2,
                     weights='uniform')

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [14]:
help(KNeighborsClassifier)

Help on class KNeighborsClassifier in module sklearn.neighbors.classification:

class KNeighborsClassifier(sklearn.neighbors.base.NeighborsBase, sklearn.neighbors.base.KNeighborsMixin, sklearn.neighbors.base.SupervisedIntegerMixin, sklearn.base.ClassifierMixin)
 |  Classifier implementing the k-nearest neighbors vote.
 |  
 |  Read more in the :ref:`User Guide <classification>`.
 |  
 |  Parameters
 |  ----------
 |  n_neighbors : int, optional (default = 5)
 |      Number of neighbors to use by default for :meth:`k_neighbors` queries.
 |  
 |  weights : str or callable, optional (default = 'uniform')
 |      weight function used in prediction.  Possible values:
 |  
 |      - 'uniform' : uniform weights.  All points in each neighborhood
 |        are weighted equally.
 |      - 'distance' : weight points by the inverse of their distance.
 |        in this case, closer neighbors of a query point will have a
 |        greater influence than neighbors which are further away.
 |      - [c

In [15]:
print(iris_X_test)

print(knn.predict(iris_X_test))

[[ 5.6  3.   4.1  1.3]
 [ 5.9  3.2  4.8  1.8]
 [ 6.3  2.3  4.4  1.3]
 [ 5.5  3.5  1.3  0.2]
 [ 5.1  3.7  1.5  0.4]
 [ 4.9  3.1  1.5  0.1]
 [ 6.3  2.9  5.6  1.8]
 [ 5.8  2.7  4.1  1. ]
 [ 7.7  3.8  6.7  2.2]
 [ 4.6  3.2  1.4  0.2]]
[1 2 1 0 0 0 2 1 2 0]
